---
title: "<span style='font-weight:bold;'><span style='color:#008040; font-size:75%;'>`r load('../common/course_info.RData'); lstCI$course_title`</span><br/>Resources</span>"
output: 
  html_document: 
    self_contained: no
    lib_dir: ../docs/slides/lib
---

<style>
ul {
  margin-left: 1em;
}
h2 {
  font-size: 20px;
  font-weight: bold;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<span style="font-size:120%;color:darkred">Do you know of other resources? If so please add them to our [workshop Etherpad](`r lstCI$etherpadfull`){target="_blank"} so we can add them to the list.</span>

### General R Tutorials

[R Basics](https://sejdemyr.github.io/r-tutorials/basics/), Simon Ejdemyr

*__swirl__*. swirl is a R package that provides tutorials right within RStudio. Install *swirl* from the 'Packages' tab in RStudio, then type *swirl()* at the console.

[R for Data Science](http://r4ds.had.co.nz/), Garrett Grolemund and Hadley Wickham

### Spatial Data in R Tutorials

[Introduction to Working With Vector Data in R](https://www.neonscience.org/vector-data-series/), NEON

[GIS in R Tutorial](http://www.nickeubank.com/gis-in-r/), Nick Eubank

[Spatial data manipulation](http://www.rspatial.org/spatial/rst/3-vectordata.html), Robert  Hijmans

[An Introduction to Spatial Data Analysis and Visualization in R](https://data.cdrc.ac.uk/tutorial/an-introduction-to-spatial-data-analysis-and-visualisation-in-r), Consumer Data Research Center

[Introduction to GIS and Spatial Analysis](https://mgimond.github.io/Spatial/index.html), Manuel Gimond

[Working with Geospatial Data in R](https://www.datacamp.com/courses/working-with-geospatial-data-in-r), DataCamp ($)

### Spatial Data Analysis

[Applied Spatial Data Analysis with R](http://www.asdar-book.org/), Roger S. Bivand, Edzer Pebesma and V. Gómez-Rubio. UseR! Series, Springer

[Geocomputation with R](http://robinlovelace.net/geocompr/), Robin Lovelace, Jakub Nowosad, and Jannes Muenchow

### R Package Reviews

[Analysis of Spatial Data](https://cran.r-project.org/web/views/Spatial.html), CRAN Task View

### Visualization

[Making maps in R tutorial](https://cengel.github.io/rspatial/4_Mapping.nb.html), Claudia Engel

[Introduction to visualising spatial data in R](https://github.com/Robinlovelace/Creating-maps-in-R), Robin  Lovelace

[Making Maps with ggplot and ggmap](http://eriqande.github.io/rep-res-web/lectures/making-maps-with-R.html),  Eric Anderson 

[tmap](https://cran.r-project.org/web/packages/tmap/vignettes/tmap-getstarted.html)

[Leaflet for R](https://rstudio.github.io/leaflet), RStudio

### RStudio

[Webinars](https://www.rstudio.com/resources/webinars/), RStudio

### R and ArcGIS

[R-ArcGIS Bridge Tutorial](https://www.youtube.com/watch?v=9lpPuCmVmxc)

[arcgisbinding R Package](https://r-arcgis.github.io/assets/arcgisbinding-vignette.html)

### Working with Specific Datasets

[Mapping US Census Data](http://zevross.com/blog/2015/10/14/manipulating-and-mapping-us-census-data-in-r-using-the-acs-tigris-and-leaflet-packages-3/), Zevross

[Cal Atlas](http://www.atlas.ca.gov/download.html)

[State of CA Geoportal](http://portal.gis.ca.gov/geoportal/catalog/search/browse/browse.page)


### Cheatsheets

[ArcGIS equivalent R functions](http://www.seascapemodels.org/data/ArcGIS_to_R_Spatial_CheatSheet.pdf), SeaScapeModels.org *

[Spatial R Remote Sensing and GIS functions](https://github.com/wegmann/RSdocs/raw/master/RSecology_cheatsheet/RS_ecology_refcard.pdf), [Remote Sensing and GIS for Ecologists](http://book.ecosens.org/) *

[Spatial Data Reference Card](https://github.com/wegmann/RSdocs/raw/master/Cheatsheet/AniMove_refcard.pdf), [AniMove](http://animove.org/) *

[R color cheatsheet](https://www.nceas.ucsb.edu/~frazier/RSpatialGuides/colorPaletteCheatsheet.pdf), Melanie Frazier *

[Overview of Coordinate Reference Systems in R](https://www.nceas.ucsb.edu/~frazier/RSpatialGuides/OverviewCoordinateReferenceSystems.pdf), Melanie Frazier *

[ggMap Quick Start](https://www.nceas.ucsb.edu/~frazier/RSpatialGuides/ggmap/ggmapCheatsheet.pdf), Melanie Frazier *

[Data Management Ultimate Cheatsheet](https://sites.ualberta.ca/~ahamann/teaching/renr690/R_Cheat_Data.pdf), Andreas Hamann *

[RStudio Cheatsheets](https://www.rstudio.com/resources/cheatsheets/), RStudio

[GIS in R Vector Functions](http://www.nickeubank.com/wp-content/uploads/2015/10/gis_in_r_vector_cheatsheet.pdf), Nick Eubank

\* = copy in our workshop 'Extras' folder

